server:
  port: 8080

zuul:
  routes:
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders:
      stripPrefix: false
    backend-service:
      path: /backend/**
      url: http://127.0.0.1:8082/
      sensitive-headers:

shuaicj.security.jwt.secret: otherpeopledontknowit
